package com.ps.entity;

import javax.persistence.Entity;
import javax.persistence.Id;

// Generated 13-Oct-2020, 5:26:55 pm by Hibernate Tools 5.4.21.Final

/**
 * Project generated by hbm2java
 */
@Entity
public class Project implements java.io.Serializable {

	@Id
	private long projid;
	private String company;
	private Double cost;
	private String location;
	private String projname;
	private Long teamsize;

	public Project() {
	}

	public Project(long projid, String company, String projname) {
		this.projid = projid;
		this.company = company;
		this.projname = projname;
	}

	public Project(long projid, String company, Double cost, String location, String projname, Long teamsize) {
		this.projid = projid;
		this.company = company;
		this.cost = cost;
		this.location = location;
		this.projname = projname;
		this.teamsize = teamsize;
	}

	public long getProjid() {
		return this.projid;
	}

	public void setProjid(long projid) {
		this.projid = projid;
	}

	public String getCompany() {
		return this.company;
	}

	public void setCompany(String company) {
		this.company = company;
	}

	public Double getCost() {
		return this.cost;
	}

	public void setCost(Double cost) {
		this.cost = cost;
	}

	public String getLocation() {
		return this.location;
	}

	public void setLocation(String location) {
		this.location = location;
	}

	public String getProjname() {
		return this.projname;
	}

	public void setProjname(String projname) {
		this.projname = projname;
	}

	public Long getTeamsize() {
		return this.teamsize;
	}

	public void setTeamsize(Long teamsize) {
		this.teamsize = teamsize;
	}

	@Override
	public String toString() {
		return "Project [projid=" + projid + ", company=" + company + ", cost=" + cost + ", location=" + location
				+ ", projname=" + projname + ", teamsize=" + teamsize + "]";
	}
	
	

}
